"""added sqlalchemy jobstorage

Revision ID: a61a658ac5b4
Revises: eb0984d07893
Create Date: 2024-07-08 14:28:48.276714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61a658ac5b4'
down_revision: Union[str, None] = 'eb0984d07893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('next_run_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('job_state', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_next_run_time'), 'jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_next_run_time'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
