"""added forecasts sections

Revision ID: eb0984d07893
Revises: efa673b05af0
Create Date: 2024-07-04 18:26:54.301571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0984d07893'
down_revision: Union[str, None] = 'efa673b05af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('received_forecasts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('forecast_rating_not_mine', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('forecast_rating_good', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('forecast_rating_excellent', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('forecast_no_reaction', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'forecast_no_reaction')
    op.drop_column('users', 'forecast_rating_excellent')
    op.drop_column('users', 'forecast_rating_good')
    op.drop_column('users', 'forecast_rating_not_mine')
    op.drop_column('users', 'received_forecasts')
    # ### end Alembic commands ###
